# Generated by Django 2.2.1 on 2019-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorimages',
            name='realtImgId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='realtors',
            name='realtId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
