# Generated by Django 2.2.1 on 2019-05-14 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=32)),
                ('phoneNo', models.IntegerField()),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipCode', models.IntegerField()),
                ('country', models.CharField(max_length=32)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Accounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
