# Generated by Django 2.2.1 on 2019-05-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
