# Generated by Django 2.2.1 on 2019-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(choices=[('1', 'Address'), ('2', 'Price'), ('3', 'Size'), ('4', 'Rooms')], default=1)),
            ],
        ),
    ]
