# Generated by Django 2.2.1 on 2019-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
